icon = "ï€®"
min_score = 100

[[categories]]
name = "work"
prefix = "w:"

[[categories]]
name = "personal"
prefix = "p:"

[[browsers]]
name = "Chrome"
command = "google-chrome-stable"
icon = "chrome-browser"
